DEBUG_MODE = True
SHOW_NOTES = True
PREFER_SIMPLE_NAMES = True
PREFER_SLASH_CHORDS = False
SHOW_UNKNOWN_VOICINGS = True
STABILIZE_MS = 60
CHORD_BUFFER_SIZE = 16
ANALYSIS_MODE = 'stateless'  # 'stateless' | 'context'
